# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
    paths: 
    - '.github/**'
    - 'main.py'
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Extract info
        uses: Dovyski/payload-info-action@master
        id: infos
        with:
          filter_push: '.commits[].modified'
          filter_pull_request: '.pull_request.commits'
      # Use the output from the `infos` step
      - name: Show extracted info
        run: |
          echo "Infos"
          echo "value: ${{ steps.infos.outputs.value }}"
          echo "branch: ${{ steps.infos.outputs.branch }}"
          echo "pull_request: ${{ steps.infos.outputs.pull_request }}"
